### ISSUE TITLE
[Bug] If user selects a "since date" too far in the past, don't attempt to load historic incident log entries - get incidents instead and restart log entry polling from the current time

### ISSUE THREAD

**Issue by gsreynolds** [PagerDuty/pd-live-react#92]

**Comment by martindstone** [comment]
I don't think this is the cause of the observed behavior. Changing the since date should always cause incidents to be fetched. I think this bug is actually because calculation of the since date for log entry polling is wrong. It's using the time of the last incident fetch. We should calculate since as whichever is the greater of "last incident fetch date" and "last fetched log entry date."
